### PR TITLE
add case for einsum taking diagonals

### PR DESCRIPTION
**Pull request by asi1024**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Thanks for the PR!
The code looks good to me, but I think it's better to keep our own benchmark code separate from ones ported from NumPy. This is to minimize the difference between NumPy/CuPy benchmark code so that it will be easy to import changes made in NumPy's benchmark code.
(actually it's updated in 18 days ago: https://github.com/numpy/numpy/tree/master/benchmarks/benchmarks)

**Comment by asi1024** [comment]
Is it OK to put the benchmark in `benchmarks/benchmarks`?

**Comment by asi1024** [comment]
I put them in `benchmarks/cupy`.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
