### PR TITLE
Add benchmark for compile_with_dtypes

### PR DESCRIPTION
**Pull request by asi1024**
Please merge after [cupy:#1382](https://github.com/cupy/cupy/pull/1382) is merged.

```
[100.00%] ··· Running cupy.bench_fusion.Fusion.time_fusion_lstm_grad_grad
[100.00%] ····
               ============= ==========
                fusion_mode
               ------------- ----------
                  enabled     615.14μs
                  disabled     5.50ms
                  compile      8.10ms
               ============= ==========
```

### CODE REVIEW

**Comment by asi1024** [comment]
Rebased.

**Comment by kmaehashi** [comment]
The code LGTM. Is it an expected behavior that `compile` is slower than other two?

**Comment by asi1024** [comment]
Yes. The time of `enabled` mode does NOT include compilation time.

**Comment by kmaehashi** [comment]
Ah, I see, so `compile` only intends to measure compilation time by recompiling the fused function.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
